### ISSUE TITLE
Doesn't work on Ruby 2.2.x

### ISSUE THREAD

**Issue by deric** [Recombee/ruby-api-client#2]
Testing gem on ruby 2.2.4:

```
ruby-api-client/lib/recombee_api_client.rb:3:in `require': cannot load such file -- digest/hmac (LoadError)
```

Seems like HMAC has been removed and `OpenSSL::HMAC.digest` from `openssl` should be used instead.

According to [the source code](https://docs.omniref.com/ruby/2.0.0.preview1/symbols/Digest::HMAC):

```
module Digest
  # = digest/hmac.rb
...
  # CAUTION: Use of this library is discouraged, because this
  # implementation was meant to be experimental but somehow got into the
  #1.9 series without being noticed.
```

**Comment by OndraFiedler** [comment]
Fixed by https://github.com/Recombee/ruby-api-client/commit/16d666cc9b764c0face2f539e3f7f69eca14a23d

**Comment by deric** [comment]
Cool, thanks!
